sudo: false
env:
  global:
    - CC_TEST_REPORTER_ID=6727774317142f42ffb6d3c2ea8764c3ef7e639ac7bff13a30d16a484439c1b9
language: ruby
rvm:
  - 2.4.3
before_install: gem install bundler -v 1.16.1
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
